# ============================================================
# ID: cf-template-001
# Nome: EC2 Instance with Security Group
# Descrição: Template CloudFormation para provisionar uma
#            instância EC2 com Security Group personalizado
# Versão: 1.0
# Autor: Ana Maísa Gomes
# Data: Outubro 2025
# ============================================================

AWSTemplateFormatVersion: '2010-09-09'
Description: 'CF-001: Instância EC2 com Security Group personalizado para Web Server'

# ============================================================
# PARAMETERS - Valores customizáveis
# ============================================================
Parameters:
  # PARAM-001: Tipo de instância
  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
    Description: 'PARAM-001: Tipo de instância EC2'
  
  # PARAM-002: AMI ID
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
    Description: 'PARAM-002: AMI mais recente do Amazon Linux 2'

# ============================================================
# RESOURCES - Recursos AWS a serem criados
# ============================================================
Resources:
  # RES-001: Security Group para Web Server
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: '[RES-001] SG para Web Server - HTTP/HTTPS/SSH'
      SecurityGroupIngress:
        # RULE-001: SSH access
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
          Description: '[RULE-001] SSH access de qualquer lugar'
        # RULE-002: HTTP access
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
          Description: '[RULE-002] HTTP traffic'
        # RULE-003: HTTPS access
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
          Description: '[RULE-003] HTTPS traffic'
      SecurityGroupEgress:
        # RULE-004: All outbound traffic
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
          Description: '[RULE-004] Permitir trafego de saida'
      Tags:
        - Key: Name
          Value: '[RES-001] WebServer-SG'
        - Key: Environment
          Value: Production
        - Key: TemplateID
          Value: 'CF-001'

  # RES-002: EC2 Instance
  WebServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref LatestAmiId
      SecurityGroups:
        - !Ref WebServerSecurityGroup
      # USERDATA-001: Script de inicialização
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          # [USERDATA-001] Instalação de Apache Web Server
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          echo "<h1>Servidor Web rodando em $(hostname -f)</h1>" > /var/www/html/index.html
      Tags:
        - Key: Name
          Value: '[RES-002] WebServer-Instance'
        - Key: Environment
          Value: Production
        - Key: TemplateID
          Value: 'CF-001'

# ============================================================
# OUTPUTS - Informações exportadas da stack
# ============================================================
Outputs:
  # OUT-001: Instance ID
  InstanceID:
    Description: '[OUT-001] ID da instancia EC2 criada'
    Value: !Ref WebServerInstance
    Export:
      Name: 'CF-001-WebServer-InstanceID'

  # OUT-002: Public IP Address
  PublicIP:
    Description: '[OUT-002] Endereco IP publico da instancia'
    Value: !GetAtt WebServerInstance.PublicIp
    Export:
      Name: 'CF-001-WebServer-PublicIP'

  # OUT-003: Security Group ID
  SecurityGroupID:
    Description: '[OUT-003] ID do Security Group criado'
    Value: !Ref WebServerSecurityGroup
    Export:
      Name: 'CF-001-WebServer-SecurityGroupID'

  # OUT-004: Website URL
  WebsiteURL:
    Description: '[OUT-004] URL para acessar o servidor web'
    Value: !Sub 'http://${WebServerInstance.PublicIp}'
    Export:
      Name: 'CF-001-WebServer-URL'
